# Задание 1. Аналитика добычи

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
pg = create_engine(
    "postgresql+psycopg2://user:pass@postgres:5432/analytics"
)

In [3]:
w = pd.read_sql("select * from wells", pg)
p = pd.read_sql("select * from production", pg)

## 1. Общая добыча по дням

In [4]:
p["dt"] = pd.to_datetime(p["date"])

prod_by_day = p \
    .groupby("date", as_index=False) \
    .agg(oil_sum=("oil_ton", "sum"),
         gas_sum=("gas_m3", "sum"),
         energy_sum=("energy_kwh", "sum")) \
    .sort_values("date")

prod_by_day.head()

         date  oil_sum   gas_sum  energy_sum
0  2025-10-01    717.5  197170.0     26730.0
1  2025-10-02    717.3  197200.0     26735.0
2  2025-10-03    719.2  197350.0     26770.0
3  2025-10-04    722.9  197810.0     26875.0
4  2025-10-05    721.0  197620.0     26810.0

## 2. KPI по скважинам
- средний дебит
- % простоя)

In [5]:
kpi = p \
    .groupby("well_id", as_index=False) \
    .agg(oil_avg=("oil_ton", "mean"),
         temp_avg=("temperature", "mean"),
         pressure_avg=("pressure", "mean"),
         downtime_sum=("downtime_hours", "sum"))

kpi["downtime_pct"] = kpi["downtime_sum"] / (30 * 24) * 100

kpi = kpi.merge(w, on="well_id", how="left")
kpi[["oil_avg", "downtime_pct"]].head()

      oil_avg  downtime_pct
0  213.150000      2.013889
1  185.816667      3.027778
2  121.696667      8.111111
3    0.000000    100.000000
4  198.430000      1.819444

# 3 Найти
- лучшие и худшие скважины
- влияние температуры и давления

In [6]:
top_w = kpi.sort_values("oil_avg", ascending=False)
top_w[["well_id", "name", "oil_avg"]].head()

   well_id      name     oil_avg
0        1  Well-101  213.150000
4        5  Well-305  198.430000
1        2  Well-102  185.816667
2        3  Well-203  121.696667
3        4  Well-304    0.000000

In [7]:
p[["oil_ton", "temperature", "pressure"]].corr()

              oil_ton  temperature  pressure
oil_ton      1.000000     0.985105  0.987107
temperature  0.985105     1.000000  0.987276
pressure     0.987107     0.987276  1.000000