# Задание 2. Прогноз дебита (ML)

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import mean_squared_error as MSE

In [2]:
pg = create_engine(
    "postgresql+psycopg2://user:pass@postgres:5432/analytics"
)

In [3]:
t = pd.read_sql("select * from well_targets", pg)
tlm = pd.read_sql("select * from well_telemetry", pg)

## 1. Подготовить dataset:
- агрегировать telemetry → день

In [4]:
t["date"] = pd.to_datetime(t["date"]).dt.date
tlm["timestamp"] = pd.to_datetime(tlm["timestamp"])
tlm["date"] = tlm["timestamp"].dt.date

tlm_day = tlm \
    .groupby(["well_id", "date"], as_index=False) \
    .agg(pressure_avg=("pressure_out", "mean"),
         temp_avg=("temperature", "mean"),
         pump_avg=("pump_speed_rpm", "mean"),
         records_cnt=("record_id", "count"))

base = t.merge(tlm_day, on=["well_id", "date"], how="inner")
base.head()

,well_id,date,daily_oil_ton,pressure_avg,temp_avg,pump_avg,records_cnt
0,1,2025-10-01,212.4,122.233333,88.2875,1472.541667,24
1,2,2025-10-01,185.9,115.516667,84.3500,1430.666667,24

## 2. Обучить модель:
- Linear Regression / RandomForest

In [5]:
cols = ["pressure_avg", "temp_avg", "pump_avg", "records_cnt"]

x = base[cols]
y = base["daily_oil_ton"]

lin_model = LinearRegression().fit(x, y)
forest_model = RandomForestRegressor().fit(x, y)

## 3. Оценить:
- MAE / RMSE

In [6]:
scores = {
    "linear model": lin_model.predict(x),
    "random forest": forest_model.predict(x),
}

for model_name, pred in scores.items():
    mae = MAE(y, pred)
    rmse = MSE(y, pred) ** 0.5

    print(model_name)
    print(f"MAE: {mae:.3f}")
    print(f"RMSE: {rmse:.3f}")
    print()

linear model
MAE: 0.000
RMSE: 0.000

random forest
MAE: 7.287
RMSE: 7.318

## 4. Сделать прогноз

In [7]:
base["lin_oil_pred"] = lin_model.predict(x)
base["rf_oil_pred"] = forest_model.predict(x)
base[["lin_oil_pred", "rf_oil_pred"]]

   lin_oil_pred  rf_oil_pred
0         212.4      204.450
1         185.9      192.525